### ISSUE TITLE
Code disappears after first run

### ISSUE THREAD

**Issue by JustinZarb** [architecture-building-systems/revitpythonshell#80]
Hi, I am using Ironpython 2.7.7 on .NET  4.0.30319.42000, in Revit 2017.2. 

I open the IronPython Console, load a script and run it successfully.  As soon as I try to edit it, the code disappears and I have to reload it, after which it works fine.

**Comment by eirannejad** [comment]
Are you using the latest RPS? This issue was addressed and resolved before: https://github.com/architecture-building-systems/revitpythonshell/issues/62

**Comment by JustinZarb** [comment]
Unfortunately I no longer have access to that computer so I cannot check that, but I downloaded the installer for Revit 2017 using the link in the readme around 06/06. Maybe the bug still exists in that version?
